# Generated by Django 5.0.3 on 2024-04-01 08:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this department should be treated as active. Unselect this instead of deleting departments.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this employee type should be treated as active. Unselect this instead of deleting employee types.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this job should be treated as active. Unselect this instead of deleting jobs.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('d_o_b', models.DateField(verbose_name='date of birth')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Widower', 'Widower')], max_length=8)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Atheist', 'Atheist'), ('Others', 'Others')], max_length=9)),
                ('nationality', models.CharField(max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(max_length=50)),
                ('employment_date', models.DateField(default=datetime.date.today, verbose_name='date of employment')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='date of resignation')),
                ('is_leave', models.BooleanField(default=False, help_text="Designates whether this employee is/isn't on leave.Select this if employee is on leave.", verbose_name='on leave')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this employee is still employed.Unselect this instead of deleting employee record.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.employeetype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.job')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to='onboarding.employee'),
        ),
    ]
