# Generated by Django 5.0.3 on 2024-04-01 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in valid format (+xxxxxxxxxxxxxx).', regex='^\\+?[1-9][0-9]{7,14}$')]),
        ),
    ]
